# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd0201a5d63c9d75fdffcade26a7478cf967c7dedfd61d8b74205953669ac4041da39a71df0526f57dcb07cfe18217993bf328e3804cb24d6ab8df822c8a928b

test:
  secret_key_base: 7a3ce7b12a6d348faa6e9e256ad9d5c769b5d4242050d75cca6875373a8a4cdfc37528f076132a6269b5812fe9e8638e699c8c3383e82c6b782f3277f12ced7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
